version: '3.8'

services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: todo-list
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    container_name: todo-list
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_DATABASE: todo-list
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:
